### ISSUE TITLE
Generated README.md in project gives incorrect npm commands

### ISSUE THREAD

**Issue by seangwright** [vue-typed/vue-typed-boilerplate#1]
The generated [README](https://github.com/vue-typed/vue-typed-boilerplate/blob/master/template/README.md) reads as follows

```
# install dependencies
npm install

# serve with hot reload at localhost:8080
npm run dev

# build for production
npm run build
```

But the [package.json](https://github.com/vue-typed/vue-typed-boilerplate/blob/master/template/package.json) has the following `scripts`

```
"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "cross-env NODE_ENV=production webpack --progress --hide-modules",
    "start": "webpack-dev-server"
  }
```

Which one is intended to be the correct set of commands?

**Comment by budiadiono** [comment]
Oops! I must be sleepy while updating the code :) the correct one is `npm start` or `npm run start`. Thanks for catching it @sgwatgit. I'll fix it now.
