### ISSUE TITLE
Source map generation needs tsconfig.json sourcemap true

### ISSUE THREAD

**Issue by pauleveritt** [vue-typed/vue-typed-boilerplate#2]
The generated project leads to a tsconfig.json file with sourceMap turned off. This causes exceptions/breakpoints to show the source and line of the ES6-generated code, instead of the original TypeScript source.

sourceMap: true fixes this.

**Comment by budiadiono** [comment]
Oh I see it, thanks for pointing out! I'm fixing it now.

**Comment by pauleveritt** [comment]
Thanks for a fast response!
